select abs(-15) from dual;
select sqrt(81) from dual;
select power(3,4) from dual;
select mod (16,5) from dual;
select ceil (-27.2) from dual;
select FLOOR(-24.2) FROM DUAL;
select ROUND(182.284,-2) FROM DUAL;
select ROUND(182.284,1) FROM DUAL;
select TRUNC(182.284,-2) FROM DUAL;
select TRUNC(182.284,-2) FROM DUAL;
select exp(4) from dual;
select length('computer engineering') from dual;
select length(name) from employee;
select lower('COMPUTER') from dual;
select lower(name) from employee;
select UPPER(name) from employee;
select UPPER('oracle11G') from dual;
select initcap('hey hello string function') from dual;
select substring('Computer Engineering',12,11) from dual;
select substring(name,0,3) from employee;
SELECT RPAD(last_name, 20, '#') AS right_justified FROM employees;
SELECT LPAD(last_name, 15, '*') AS left_justified FROM employees;
SELECT REPLACE('greatest', 'gbrsea', '') AS removed_chars FROM dual;
SELECT REPLACE('government', 'ornt', 'xynt') AS changed_chars FROM dual;
SELECT REPLACE('government', 'govern', 'suppli') AS replaced_word FROM dual;
SELECT ASCII('s') AS ascii_s FROM dual;
SELECT ASCII('A') AS ascii_A FROM dual;
SELECT ASCII('a') AS ascii_a FROM dual;
SELECT INSTR('Database', 'base') AS first_occurrenc FROM dual;