SELECT ABS(-15) FROM DUAL;
SELECT SQRT(81) FROM DUAL;
SELECT POWER(3,4) FROM DUAL;
SELECT MOD (16,5) FROM DUAL;
SELECT CEIL (-27.2) FROM DUAL;
SELECT FLOOR(-24.2) FROM DUAL;
SELECT ROUND(182.284,-2) FROM DUAL;
SELECT ROUND(182.284,1) FROM DUAL;
SELECT TRUNC(182.284,-2) FROM DUAL;
SELECT TRUNC(182.284,-2) FROM DUAL;
SELECT EXP(4) FROM DUAL;
SELECT LENGTH('computer engineering') FROM DUAL;
SELECT LENGTH(name) FROM employee;
SELECT LOWER('COMPUTER') FROM DUAL;
SELECT LOWER(name) FROM employee;
SELECT UPPER(name) FROM employee;
SELECT UPPER('oracle11G') FROM DUAL;
SELECT INITCAP('hey hello string function') FROM DUAL;
SELECT SUBSTRING('Computer Engineering',12,11) FROM DUAL;
SELECT SUBSTRING(name,0,3) FROM employee;
SELECT RPAD(last_name, 20, '#') AS right_justified FROM employees;
SELECT LPAD(last_name, 15, '*') AS left_justified FROM employees;
SELECT REPLACE('greatest', 'gbrsea', '') AS removed_chars FROM DUAL;
SELECT REPLACE('government', 'ornt', 'xynt') AS changed_chars FROM DUAL;
SELECT REPLACE('government', 'govern', 'suppli') AS replaced_word FROM DUAL;
SELECT ASCII('s') AS ascii_s FROM DUAL;
SELECT ASCII('A') AS ascii_A FROM DUAL;
SELECT ASCII('a') AS ascii_a FROM DUAL;
SELECT INSTR('Database', 'base') AS first_occurrenc FROM DUAL;